version: '3'
services:
  web:
    build: .
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - php
  php:
    image: php:7.2-fpm-alpine
    volumes:
      - ./html:/var/www/html
