name: Digital Ocean Droplet CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - run: npm ci
      - run: npm run build
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }} 
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }} 
          script: |
            cd /var/www/toolloaner/backend
            git pull
            npm ci
            pm2 restart all
