name: Digital Ocean Droplet CD

on:
  push:
    branches: [main] #runs on every push on the main branch

debug: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.  USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/toolloaner/backend
            git pull
            npm ci
            pm2 restart all
