name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret 1
        run: echo ${{ secrets.DATABASE_URL }}
      - name Use secret 2
        run: echo ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      - name Use secret 3
        run: echo ${{ secrets.CLOUDINARY_API_KEY }}
      - name Use secret 4
        run: echo ${{ secrets.CLOUDINARY_API_SECRET }}

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - run: npm ci
      - run: npm test
      - run: npm run build
