name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "19"
      - run: npm ci
      - run: npm test
      - run: npm run build
