name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret 1
        run: echo ${{ secrets.DATABASE_URL }}


      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "19"
      - run: npm ci
      - run: npm test
      - run: npm run build
